---
- hosts: wordpress
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes
  tasks:
    - name: Install dependencias
      ansible.builtin.apt:
        pkg:
          - apache2
          - ghostscript
          - libapache2-mod-php
          - php
          - php-bcmath
          - php-curl
          - php-imagick
          - php-intl
          - php-json
          - php-mbstring
          - php-mysql
          - php-xml
          - php-zip
        state: latest
        update-cache: yes
      #become é utilizado para comandos Sudo
      become: yes

    - name: Cria uma pasta
      ansible.builtin.file:
        path: /srv/www
        state: directory
        owner: www-data
        group: www-data
      become: yes

    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /srv/www
        remote_src: yes
      become: yes

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: files/wordpress.conf
        dest: /etc/apache2/sites-available/000-default.conf
        #Evita que force a copia do arquivo
        force: yes
      become: yes
      notify:
        - restart apache

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /srv/www/wordpress/wp-config-sample.php
        dest: /srv/www/wordpress/wp-config.php
        #Faz a cópia da maquina remota para outra maquina remota
        remote_src: yes
        force: no
      become: yes

    - name: Configure wp-config with database
      ansible.builtin.replace:
        path: /srv/www/wordpress/wp-config.php
        regexp: "{{item.regexp}}"
        replace: "{{item.replace}}"
      with_items:
        - { regexp: "database_name_here", replace: "wordpress_db" }
        - { regexp: "username_here", replace: "wordpress_user" }
        - { regexp: "password_here", replace: "12345" }
        - { regexp: "localhost", replace: "192.168.0.16" }
      become: yes

    - name: Replace a localhost entry searching for a literal string to avoid escaping
      ansible.builtin.lineinfile:
        path: /srv/www/wordpress/wp-config.php
        search_string: "{{item.search_string}}"
        line: "{{item.line}}"
      with_items:
        - {
            search_string: "define( 'AUTH_KEY',         'put your unique phrase here' );",
            line: "define('AUTH_KEY',         'Yk4BN^c>Sa-y# <H(7RbFT=`x~fz@HE-]<u*l$)r)%OB1Vz[-D]V]QW|.]5a6H30');",
          }
        - {
            search_string: "define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );",
            line: "define('SECURE_AUTH_KEY',  'Hy`4vBfn&IPr<kw+s(uNvGp%L}^r4,$Lg]  %xFy|y@ oVE:rN7 K)11Q1.9I4R)');",
          }
        - {
            search_string: "define( 'LOGGED_IN_KEY',    'put your unique phrase here' );",
            line: "define('LOGGED_IN_KEY',    'PB wZ]0`{+v@DHv~:c4u+.Qz|Uh!o9#{144cRF^c#|w1_l<d~s>-KqtQzwdLh}Vq');",
          }
        - {
            search_string: "define( 'NONCE_KEY',        'put your unique phrase here' );",
            line: "define('NONCE_KEY',        'q^mx.2A<! p7%[y/g2<7#3EsghRL&QE3|6w_<M.R*?G-24^`C_j*FJA@+_`kR=7{');",
          }
        - {
            search_string: "define( 'AUTH_SALT',        'put your unique phrase here' );",
            line: "define('AUTH_SALT',        '/n+G]YaUx7iV@KD|}a`M+!qpa-__byH(-S!OS~THBV>/|z4wg{SYfo!@AjPSsDSk');",
          }
        - {
            search_string: "define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );",
            line: "define('SECURE_AUTH_SALT', '|;1qa%4V)Wh_};+L6xD`s <emf;szri$d_+6>h-[~DY#n5&`$0Y7Manu(FSYbZ_%');",
          }
        - {
            search_string: "define( 'LOGGED_IN_SALT',   'put your unique phrase here' );",
            line: "define('LOGGED_IN_SALT',   'ZtW%Ntk+2hE8MNBx1t4p8w#y=f90$@enz(~B/PRj7=<*-:E2-PH[/0$J->+@@6>B');",
          }
        - {
            search_string: "define( 'NONCE_SALT',       'put your unique phrase here' );",
            line: "define('NONCE_SALT',       'A}e[FT35vwq:0@QF{T7MnN7gAG+(*klGhC&[$_XapqnE8uE-_];GG6JC]NC0[tU_');",
          }
      become: yes

- hosts: mysql
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes
  tasks:
    - name: Install dependencias
      ansible.builtin.apt:
        pkg:
          - mysql-server
          - python3-pymysql
        state: latest
        update-cache: yes
      #become é para comandos Sudo
      become: yes

    - name: Create a new database with name 'wordpress_db'
      community.mysql.mysql_db:
        name: wordpress_db
        state: present
        #absent apagaria o banco de dados e criaria uma nova
        #present caso ja exista ele não cria
        login_unix_socket: /run/mysqld/mysqld.sock
      become: yes

    - name: Create database user with name 'wordpress_user' and password '12345' with all database privileges
      community.mysql.mysql_user:
        name: wordpress_user
        password: 12345
        #O previlégio priv: '*.*:ALL' da permissão para alterar tudo no banco de dados
        #Para restringir altere para "wordpress_db.*" para dar acesso apenas para esse DB  e "ALL" para os coomandos chave que esse usuário vai executar
        priv: "*wordpress_db.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
        state: absent
        #Login_unix_socket é utilizado para se conectar ao banco de dados
        login_unix_socket: /run/mysqld/mysqld.sock
        host: "{{ item }}"
      with_items:
        - "localhost"
        - "127.0.0.1"
        - "192.168.0.17"
      become: yes

    - name: Configure Database
      ansible.builtin.replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"
      become: yes
      notify:
        - restart mysql
